# Generated by Django 5.2.1 on 2025-06-07 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short professional biography', null=True, verbose_name='biography')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers/profile_pictures/', verbose_name='profile picture')),
                ('hire_date', models.DateField(blank=True, help_text='Date when the teacher was hired', null=True, verbose_name='date hired')),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='years of experience')),
                ('specialization', models.CharField(blank=True, help_text='Primary subject or field of expertise', max_length=100, null=True, verbose_name='specialization')),
                ('office_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='office location')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this teacher is currently active', verbose_name='active status')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the teacher', null=True, verbose_name='administrative notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
        ),
    ]
