# Generated by Django 5.2.1 on 2025-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherprofile_email_teacherprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='years_of_experience',
        ),
    ]
