# Generated by Django 5.2.1 on 2025-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsection_class_name_and_more'),
        ('teacher', '0003_remove_teacherprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='class_allocated',
            field=models.ManyToManyField(blank=True, null=True, to='academics.classname'),
        ),
    ]
