# Generated by Django 5.2.1 on 2025-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsection_class_name_and_more'),
        ('teacher', '0005_alter_teacherprofile_class_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='class_allocated',
            field=models.ManyToManyField(blank=True, null=True, to='academics.courseoffering'),
        ),
    ]
