# Generated by Django 5.2.1 on 2025-06-07 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('for_all', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('for_class', models.ManyToManyField(blank=True, related_name='announcement_for_class', to='academics.classname')),
                ('for_section', models.ManyToManyField(blank=True, related_name='announcement_for_section', to='academics.section')),
            ],
        ),
    ]
