# Generated by Django 5.2.1 on 2025-06-21 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsection'),
        ),
    ]
