# Generated by Django 5.2.1 on 2025-06-22 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_courseoffering_class_info'),
        ('teacher', '0003_remove_teacherprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classname'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classsection'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile'),
        ),
    ]
