# Generated by Django 5.2.1 on 2025-06-22 00:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsection_class_name_and_more'),
        ('student', '0003_studentprofile_current_class'),
        ('teacher', '0006_alter_teacherprofile_class_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student'], name='academics_a_student_7ec26d_idx'), models.Index(fields=['date'], name='academics_a_date_fdcc90_idx'), models.Index(fields=['course_offering'], name='academics_a_course__19c901_idx')],
                'unique_together': {('student', 'course_offering', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CurrentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student'], name='academics_c_student_55f965_idx'), models.Index(fields=['date'], name='academics_c_date_d7263b_idx'), models.Index(fields=['course_offering'], name='academics_c_course__de65c6_idx')],
                'unique_together': {('student', 'course_offering', 'date')},
            },
        ),
    ]
