# Generated by Django 5.2.1 on 2025-06-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_archivedattendance_currentattendance'),
        ('teacher', '0006_alter_teacherprofile_class_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
                ('class_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classsection')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacherprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.periodslot')),
            ],
            options={
                'ordering': ['day_of_week', 'period__start_time'],
                'unique_together': {('class_info', 'day_of_week', 'period')},
            },
        ),
    ]
