# Generated by Django 5.2.1 on 2025-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_periodslot_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
