# Generated by Django 5.2.1 on 2025-05-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_class',
        ),
    ]
