# Generated by Django 5.2.1 on 2025-06-22 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classsection_class_name_and_more'),
        ('student', '0002_studentprofile_email_studentprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classsection'),
        ),
    ]
